import { useEffect, useState } from "react";
import Sidebar, { navGroups } from "./components/layout/Sidebar";
import { evaluateDecision, listFreightForecasts, recordHumanDecision, type DecisionResponse, type FreightForecast, type HumanDecisionResponse } from "./api";
import type { ProcurementContext } from "./pages/NewProcurement";
import NewProcurement from "./pages/NewProcurement";
import MarketIntelligence from "./pages/MarketIntelligence";
import FreightForecast from "./pages/FreightForecast";
import PortIntelligence from "./pages/PortIntelligence";
import VesselDirectory from "./pages/VesselDirectory";
import CostCharting from "./pages/CostCharting";
import WhatIfRisk from "./pages/WhatIfRisk";
import AIRecommendation from "./pages/AIRecommendation";
import DecisionHistory from "./pages/DecisionHistory";
import ActualOutcomes from "./pages/ActualOutcomes";
import ModelPerformance from "./pages/ModelPerformance";

function CommandCenter({ procurement, decision, onDecision, human, onHuman, navigate }: { procurement: ProcurementContext | null; decision: DecisionResponse | null; onDecision: (d: DecisionResponse) => void; human: HumanDecisionResponse | null; onHuman: (d: HumanDecisionResponse) => void; navigate: (id: string) => void }) {
  const [waitDays, setWaitDays] = useState(7); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function run() { if (!procurement) return; setBusy(true); setError(""); try { const forecasts = await listFreightForecasts(); const d = await evaluateDecision(procurement.cargo.quantity_mt, waitDays, procurement.cargo.id, forecasts[0]?.id); onDecision(d); } catch (e) { setError(e instanceof Error ? e.message : "Decision engine unavailable."); } finally { setBusy(false); } }
  async function act(action: "APPROVE" | "MODIFY" | "REJECT") { if (!decision?.decision_run_id) return; try { onHuman(await recordHumanDecision(decision.decision_run_id, action, `${action} from CharterPulse Command Center.`)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to record human decision."); } }
  if (!procurement) return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">COMMAND CENTER</span><h1>Decision Room</h1><p>Create a procurement requirement first. The decision room never fills missing data with invented values.</p></div></div><section className="hero-command"><div><span className="eyebrow">FROM CARGO REQUIREMENT → BEST TRANSPORTATION DECISION</span><h2>Start the procurement intelligence workflow.</h2><p>Material → country → port → delivery window → forecast → vessel → cost → risk → human approval.</p></div><button className="primary-button" onClick={() => navigate("New Procurement")}>NEW PROCUREMENT</button></section></div>;
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">COMMAND CENTER / DECISION ROOM</span><h1>{procurement.cargo.material} procurement</h1><p>{procurement.cargo.quantity_mt.toLocaleString()} MT · {procurement.originPort.name} → {procurement.destinationPort.name}</p></div><span className={`data-badge ${decision?.provenance === "SIMULATED" ? "simulated" : "real"}`}>{decision?.provenance || "READY"}</span></div><div className="metric-grid four"><div className="metric-card"><span>DELIVERY</span><strong>{new Date(procurement.cargo.earliest_delivery || "").toLocaleDateString("en-GB")}</strong><small>to {new Date(procurement.cargo.latest_delivery || "").toLocaleDateString("en-GB")}</small></div><div className="metric-card"><span>FREIGHT P50</span><strong>{decision ? `$${decision.forecast_p50.toFixed(2)}` : "—"}</strong><small>USD/MT</small></div><div className="metric-card"><span>RISK</span><strong>{decision ? decision.risk_score.toFixed(1) : "—"}</strong><small>0–100</small></div><div className="metric-card"><span>RECOMMENDATION</span><strong>{decision ? decision.recommendation.replace(/_/g, " ") : "READY"}</strong><small>{human ? `Human: ${human.action}` : "Human approval required"}</small></div></div><section className="enterprise-card"><div className="section-head"><div><span className="eyebrow">OPTIMIZATION CONTROL</span><h2>Now vs wait</h2></div><button className="primary-button compact-button" onClick={run} disabled={busy}>{busy ? "RUNNING…" : "RUN DECISION"}</button></div><div className="control-row"><label>WAIT HORIZON <strong>{waitDays} days</strong><input type="range" min="1" max="30" value={waitDays} onChange={e => setWaitDays(Number(e.target.value))}/></label></div>{decision && <div className="decision-grid"><div><span>NOW P50 COST</span><strong>${decision.now_expected_freight_cost.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div><div><span>WAIT CONSERVATIVE</span><strong>${decision.wait_conservative_cost.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div><div><span>WAIT DIFFERENCE</span><strong>${decision.wait_cost_difference.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div><div><span>PROBABILITY NOW &gt; BASELINE</span><strong>{(decision.probability_now_exceeds_baseline * 100).toFixed(1)}%</strong></div></div>}{error && <div className="error-banner">{error}</div>}</section>{decision && <section className="enterprise-card"><div className="section-head"><div><span className="eyebrow">HUMAN GOVERNANCE</span><h2>Approve, modify or reject</h2></div><span className="field-note">No autonomous contracting</span></div><div className="button-row"><button className="primary-button" onClick={() => act("APPROVE")}>APPROVE</button><button className="secondary-button" onClick={() => act("MODIFY")}>MODIFY</button><button className="danger-button" onClick={() => act("REJECT")}>REJECT</button></div></section>}</div>;
}

export default function App() {
  const [active, setActive] = useState("Command Center"); const [procurement, setProcurement] = useState<ProcurementContext | null>(null); const [decision, setDecision] = useState<DecisionResponse | null>(null); const [human, setHuman] = useState<HumanDecisionResponse | null>(null); const [forecast, setForecast] = useState<FreightForecast | null>(null);
  useEffect(() => { listFreightForecasts().then(f => setForecast(f[0] || null)).catch(() => setForecast(null)); }, [decision]);
  async function created(p: ProcurementContext) { setProcurement(p); setActive("Command Center"); try { const forecasts = await listFreightForecasts(); const d = await evaluateDecision(p.cargo.quantity_mt, 7, p.cargo.id, forecasts[0]?.id); setDecision(d); } catch { setDecision(null); } }
  function content() { switch (active) { case "New Procurement": return <NewProcurement onCreated={created}/>; case "Market Intelligence": return <MarketIntelligence/>; case "Freight Forecast": return <FreightForecast/>; case "Port Intelligence": return <PortIntelligence/>; case "Vessel Intelligence": return <VesselDirectory/>; case "Cost & Chartering": return <CostCharting/>; case "What-If & Risk": return <WhatIfRisk decision={decision}/>; case "AI Recommendation": return <AIRecommendation procurement={procurement} decision={decision} onDecision={setDecision}/>; case "Decision History": return <DecisionHistory procurement={procurement} decision={decision} human={human}/>; case "Actual Outcomes": return <ActualOutcomes procurement={procurement} decision={decision}/>; case "Model Performance": return <ModelPerformance forecast={forecast}/>; default: return <CommandCenter procurement={procurement} decision={decision} onDecision={setDecision} human={human} onHuman={setHuman} navigate={setActive}/>; } }
  return <div className="enterprise-app"><Sidebar active={active} onNavigate={setActive}/><main className="enterprise-main"><div className="top-status"><span><i className="status-dot"/> CONNECTED</span><span>SAIL · CHARTERPULSE AI</span></div>{content()}</main></div>;
}
