import { useEffect, useMemo, useState } from "react";
import { evaluateDecision, listFreightForecasts, listVessels, type DecisionResponse, type FreightForecast, type Vessel } from "../api";
import type { ProcurementContext } from "./NewProcurement";
export default function AIRecommendation({ procurement, decision, onDecision }: { procurement: ProcurementContext | null; decision: DecisionResponse | null; onDecision: (d: DecisionResponse) => void }) {
  const [forecasts, setForecasts] = useState<FreightForecast[]>([]); const [vessels, setVessels] = useState<Vessel[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([listFreightForecasts(), listVessels()]).then(([f, v]) => { setForecasts(f); setVessels(v); }).catch(() => undefined); }, []);
  const forecast = forecasts[0]; const recommendedVessel = useMemo(() => vessels.filter(v => (v.cargo_capacity_mt || v.dwt || 0) >= (procurement?.cargo.quantity_mt || 0)).sort((a, b) => (a.cargo_capacity_mt || a.dwt || 0) - (b.cargo_capacity_mt || b.dwt || 0))[0] || vessels.find(v => String(v.vessel_class).toLowerCase().includes("panamax")), [vessels, procurement]);
  async function run() { if (!procurement || !forecast) return; setBusy(true); setError(""); try { onDecision(await evaluateDecision(procurement.cargo.quantity_mt, 7, procurement.cargo.id, forecast.id)); } catch (e) { setError(e instanceof Error ? e.message : "Decision engine unavailable."); } finally { setBusy(false); } }
  const savings = decision?.wait_cost_difference ?? 0; const strategy = decision?.recommendation === "CHARTER_NOW" ? "Spot / short-period charter with immediate fixture review" : "Delay commitment; retain optionality and re-price before laycan";
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">DECISION / AI RECOMMENDATION</span><h1>AI Recommendation</h1><p>The recommendation is bound to the active procurement, forecast record and optimizer response.</p></div>{decision && <span className="data-badge proxy">{decision.provenance}</span>}</div>{procurement ? <section className="enterprise-card decision-hero"><div><span className="eyebrow">RECOMMENDATION</span><h2>{decision ? decision.recommendation.replace(/_/g, " ") : "READY TO EVALUATE"}</h2><p>{decision?.rationale?.[0] || "Run the decision engine to evaluate charter timing against the forecast distribution."}</p></div><button className="primary-button" onClick={run} disabled={busy || !forecast}>{busy ? "OPTIMIZING…" : "RUN OPTIMIZATION"}</button></section> : <section className="enterprise-card"><h2>No active procurement</h2><p>Create a requirement first so the recommendation is tied to a real cargo record.</p></section>}{decision && <div className="metric-grid four"><div className="metric-card"><span>CHARTER DECISION</span><strong>{decision.recommendation === "CHARTER_NOW" ? "CHART NOW" : decision.recommendation.replace(/_/g, " ")}</strong><small>Timing recommendation</small></div><div className="metric-card"><span>VESSEL</span><strong>{recommendedVessel?.vessel_class || recommendedVessel?.name || "REVIEW"}</strong><small>{recommendedVessel?.cargo_capacity_mt?.toLocaleString() || recommendedVessel?.dwt?.toLocaleString() || "—"} MT capacity</small></div><div className="metric-card"><span>EXPECTED SAVINGS</span><strong>${Math.max(0, savings).toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong><small>vs conservative wait case</small></div><div className="metric-card"><span>RISK SCORE</span><strong>{decision.risk_score.toFixed(1)}</strong><small>0–100 decision risk</small></div></div>}{decision && <section className="enterprise-card"><div className="recommendation-grid"><div><span className="eyebrow">CONTRACT STRATEGY</span><h3>{strategy}</h3><p>Final contracting remains a human commercial decision.</p></div><div><span className="eyebrow">WHY</span><ul>{decision.rationale.map((r, i) => <li key={i}>{r}</li>)}</ul></div><div><span className="eyebrow">WARNINGS</span><ul>{decision.warnings.map((r, i) => <li key={i}>{r}</li>)}</ul></div></div></section>}{error && <div className="error-banner">{error}</div>}</div>;
}
