import { useEffect, useMemo, useState } from "react";
import { listFreightForecasts, listPorts, type FreightForecast, type Port } from "../api";
import { PUBLIC_MARKET_BASELINE, PUBLIC_VESSEL_REFERENCES } from "../data/publicMarket";
const rad = (v: number) => v * Math.PI / 180;
const nm = (a: Port, b: Port) => { if (a.latitude == null || a.longitude == null || b.latitude == null || b.longitude == null) return null; const dLat = rad(b.latitude - a.latitude); const dLon = rad(b.longitude - a.longitude); const x = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(dLon / 2) ** 2; return 3440.065 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); };
export default function CostCharting() {
  const [ports, setPorts] = useState<Port[]>([]); const [forecasts, setForecasts] = useState<FreightForecast[]>([]); const [origin, setOrigin] = useState(""); const [destination, setDestination] = useState(""); const [vesselClass, setVesselClass] = useState("Panamax"); const [quantity, setQuantity] = useState(70000);
  useEffect(() => { Promise.all([listPorts(), listFreightForecasts()]).then(([p, f]) => { setPorts(p); setForecasts(f); }).catch(() => undefined); }, []);
  const op = ports.find(p => p.id === origin); const dp = ports.find(p => p.id === destination); const distance = op && dp ? nm(op, dp) : null; const ref = PUBLIC_VESSEL_REFERENCES.find(x => x.className === vesselClass) || PUBLIC_VESSEL_REFERENCES[0]; const speed = vesselClass === "Capesize" ? 13 : vesselClass === "Handysize" ? 12 : 13; const days = distance ? (distance * 2) / (speed * 24) : null; const latestBunker = useMemo(() => PUBLIC_MARKET_BASELINE.filter(x => x.metric === "Singapore VLSFO").sort((a, b) => b.date.localeCompare(a.date))[0], []); const bunkerRate = latestBunker?.value ?? 842; const bunker = days ? days * ref.fuel * bunkerRate : null; const freight = forecasts[0] ? forecasts[0].p50 * quantity : null; const knownTotal = (freight || 0) + (bunker || 0);
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">DECISION / COST ENGINE</span><h1>Cost & Chartering</h1><p>Known route inputs are calculated dynamically. Unsourced port, canal and demurrage values are not invented.</p></div><span className="data-badge proxy">DERIVED + PUBLIC PROXY</span></div><section className="enterprise-card"><div className="form-grid four"><div className="field"><label>ORIGIN PORT</label><select value={origin} onChange={e => setOrigin(e.target.value)}><option value="">Select port</option>{ports.slice(0, 1000).map(p => <option key={p.id} value={p.id}>{p.name} · {p.unlocode || "—"}</option>)}</select></div><div className="field"><label>DESTINATION PORT</label><select value={destination} onChange={e => setDestination(e.target.value)}><option value="">Select port</option>{ports.slice(0, 1000).map(p => <option key={p.id} value={p.id}>{p.name} · {p.unlocode || "—"}</option>)}</select></div><div className="field"><label>VESSEL CLASS</label><select value={vesselClass} onChange={e => setVesselClass(e.target.value)}><option>Panamax</option><option>Capesize</option><option>Handysize</option></select></div><div className="field"><label>CARGO</label><div className="input-unit"><input type="number" min="1" value={quantity} onChange={e => setQuantity(Number(e.target.value))}/><span>MT</span></div></div></div></section><div className="waterfall-grid"><div className="cost-waterfall"><div className="cost-row"><span>Ocean freight · forecast P50</span><strong>{freight == null ? "—" : `$${freight.toLocaleString(undefined, { maximumFractionDigits: 0 })}`}</strong></div><div className="cost-row"><span>Bunker · Singapore VLSFO public proxy</span><strong>{bunker == null ? "—" : `$${bunker.toLocaleString(undefined, { maximumFractionDigits: 0 })}`}</strong></div><div className="cost-row muted"><span>Port charges · source required</span><strong>NOT SOURCED</strong></div><div className="cost-row muted"><span>Canal dues · route dependent</span><strong>NOT SOURCED</strong></div><div className="cost-row muted"><span>Demurrage risk buffer · source required</span><strong>NOT SOURCED</strong></div><div className="cost-total"><span>KNOWN COST</span><strong>${knownTotal.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong><small>{quantity.toLocaleString()} MT · known-cost subtotal only</small></div></div><section className="enterprise-card cost-context"><span className="eyebrow">ROUTE PHYSICS</span><h2>{distance == null ? "Select both ports" : `${distance.toFixed(0)} nautical miles`}</h2><p>{days == null ? "Coordinates are required for a bunker estimate." : `${days.toFixed(1)} days round-trip at ${speed} kn reference speed.`}</p><p>Reference fuel: {ref.fuel} MT/day · {ref.vessel} · VLSFO ${bunkerRate}/MT.</p><span className="data-badge proxy">PUBLIC_PROXY / DERIVED</span></section></div></div>;
}
