import { useEffect, useMemo, useState } from "react";
import { listFreightForecasts, listMarketObservations, type FreightForecast, type MarketObservation } from "../api";

function LineChart({ forecast, history }: { forecast: FreightForecast; history: MarketObservation[] }) {
  const points = history.filter(x => x.value > 0).slice(-10).map(x => ({ label: x.observed_at.slice(5, 10), p50: x.value, p10: x.value, p90: x.value }));
  const base = points.length ? points[points.length - 1].p50 : forecast.baseline;
  const future = [0, 1, 2, 3, 4].map(i => ({ label: `+${i + 1}w`, p50: base + (forecast.p50 - base) * ((i + 1) / 5), p10: forecast.p10 + (base - forecast.p10) * Math.max(0, 1 - (i + 1) / 5), p90: forecast.p90 - (forecast.p90 - base) * Math.max(0, 1 - (i + 1) / 5) }));
  const data = [...points, ...future]; const min = Math.min(...data.map(x => x.p10)); const max = Math.max(...data.map(x => x.p90)); const w = 900; const h = 300; const x = (i: number) => 40 + i * ((w - 70) / Math.max(1, data.length - 1)); const y = (v: number) => h - 30 - ((v - min) / Math.max(0.0001, max - min)) * (h - 55); const path = (key: "p10" | "p50" | "p90") => data.map((d, i) => `${i ? "L" : "M"}${x(i)},${y(d[key])}`).join(" "); const split = Math.max(0, points.length - 1); return <div className="chart-shell"><svg viewBox={`0 0 ${w} ${h}`} className="forecast-svg" role="img" aria-label="Historical and forecast freight curve"><line x1="40" x2="870" y1={h - 30} y2={h - 30} className="chart-axis"/><line x1={x(split)} x2={x(split)} y1="15" y2={h - 30} className="chart-divider"/><path d={path("p10")} className="chart-line lower"/><path d={path("p90")} className="chart-line upper"/><path d={path("p50")} className="chart-line median"/>{data.map((d, i) => <text key={i} x={x(i)} y={h - 8} className="chart-label" textAnchor="middle">{d.label}</text>)}<text x={x(split) + 8} y="28" className="chart-label">FORECAST →</text></svg><div className="chart-legend"><span><i className="legend-median"/>P50</span><span><i className="legend-band"/>P10–P90 confidence band</span><span>USD/MT</span></div></div>;
}
export default function FreightForecast() {
  const [forecasts, setForecasts] = useState<FreightForecast[]>([]); const [observations, setObservations] = useState<MarketObservation[]>([]); const [selected, setSelected] = useState<FreightForecast | null>(null);
  useEffect(() => { Promise.all([listFreightForecasts(), listMarketObservations()]).then(([f, o]) => { setForecasts(f); setObservations(o); setSelected(f[0] || null); }).catch(() => undefined); }, []);
  const freightHistory = useMemo(() => observations.filter(x => x.metric.toLowerCase().includes("freight")), [observations]);
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">MARKET INTELLIGENCE / FORECAST</span><h1>Freight Forecast</h1><p>Historical observations transition into quantile forecasts. Confidence is shown from the forecast record rather than invented.</p></div>{selected && <span className={`data-badge ${selected.provenance === "SIMULATED" ? "simulated" : "real"}`}>{selected.provenance}</span>}</div>{selected ? <><div className="metric-grid four"><div className="metric-card"><span>P10</span><strong>{selected.p10.toFixed(2)}</strong><small>Lower scenario · USD/MT</small></div><div className="metric-card"><span>P50</span><strong>{selected.p50.toFixed(2)}</strong><small>Median · USD/MT</small></div><div className="metric-card"><span>P90</span><strong>{selected.p90.toFixed(2)}</strong><small>Upper scenario · USD/MT</small></div><div className="metric-card"><span>CONFIDENCE</span><strong>{selected.confidence == null ? "—" : `${(selected.confidence * 100).toFixed(1)}%`}</strong><small>{selected.model_name || "Forecast model"}</small></div></div><section className="enterprise-card"><div className="section-head"><div><span className="eyebrow">TREND ENGINE</span><h2>Freight scenario curve</h2></div><select value={selected.id} onChange={e => setSelected(forecasts.find(x => x.id === e.target.value) || selected)}>{forecasts.map(f => <option key={f.id} value={f.id}>{f.model_name || f.id} · {f.generated_at.slice(0, 10)}</option>)}</select></div><LineChart forecast={selected} history={freightHistory}/><div className="forecast-meta"><span>MAE <strong>{selected.mae?.toFixed(2) ?? "—"}</strong></span><span>RMSE <strong>{selected.rmse?.toFixed(2) ?? "—"}</strong></span><span>sMAPE <strong>{selected.smape?.toFixed(2) ?? "—"}%</strong></span><span>Coverage <strong>{selected.interval_coverage == null ? "Pending OOS test" : `${(selected.interval_coverage * 100).toFixed(1)}%`}</strong></span></div></section></> : <section className="enterprise-card"><h2>No forecast record returned</h2><p>Connect a forecast provider/model run before presenting a live freight curve.</p></section>}</div>;
}
