import { useEffect, useMemo, useState } from "react";
import { listMarketObservations, type MarketObservation } from "../api";
import { PUBLIC_MARKET_BASELINE } from "../data/publicMarket";
const money = (v: number) => `$${v.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;
export default function MarketIntelligence() {
  const [live, setLive] = useState<MarketObservation[]>([]); const [metricFilter, setMetricFilter] = useState("ALL"); const [provenanceFilter, setProvenanceFilter] = useState("ALL");
  useEffect(() => { listMarketObservations().then(setLive).catch(() => setLive([])); }, []);
  const allRows = useMemo(() => [...PUBLIC_MARKET_BASELINE.map((x, i) => ({ id: `proxy-${i}`, metric: x.metric, value: x.value, unit: x.unit, currency: x.currency, observed_at: x.date, source: x.source, provenance: x.provenance })), ...live].sort((a, b) => String(b.observed_at).localeCompare(String(a.observed_at))), [live]);
  const metrics = useMemo(() => Array.from(new Set(allRows.map(r => r.metric))), [allRows]);
  const rows = useMemo(() => allRows.filter(r => (metricFilter === "ALL" || r.metric === metricFilter) && (provenanceFilter === "ALL" || r.provenance === provenanceFilter)).slice(0, 100), [allRows, metricFilter, provenanceFilter]);
  const latest = metrics.map(metric => allRows.find(r => r.metric === metric)).filter(Boolean) as typeof allRows;
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">MARKET INTELLIGENCE</span><h1>Market Intelligence</h1><p>Historical public benchmarks are visible immediately; stored API observations remain labelled with their actual provenance.</p></div><span className="data-badge proxy">PUBLIC PROXY + API</span></div><div className="metric-grid three">{latest.map(r => <div className="metric-card" key={r.metric}><span>{r.metric}</span><strong>{r.unit === "INDEX" ? r.value.toLocaleString() : money(r.value)}</strong><small>{r.observed_at} · {r.provenance}</small></div>)}</div><section className="enterprise-card"><div className="section-head"><div><span className="eyebrow">OBSERVATIONS</span><h2>Cross-market baseline</h2></div><span className="field-note">{rows.length} visible records</span></div><div className="form-grid two"><div className="field"><label>METRIC FILTER</label><select value={metricFilter} onChange={e => setMetricFilter(e.target.value)}><option value="ALL">All market metrics</option>{metrics.map(m => <option key={m}>{m}</option>)}</select></div><div className="field"><label>PROVENANCE</label><select value={provenanceFilter} onChange={e => setProvenanceFilter(e.target.value)}><option value="ALL">All provenance</option><option value="REAL">REAL</option><option value="PUBLIC_PROXY">PUBLIC_PROXY</option><option value="SIMULATED">SIMULATED</option></select></div></div><div className="table-wrap"><table><thead><tr><th>Metric</th><th>Observed</th><th>Value</th><th>Unit</th><th>Provenance</th><th>Source</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td className="strong">{r.metric}</td><td>{new Date(r.observed_at).toLocaleDateString("en-GB")}</td><td>{r.unit === "INDEX" ? r.value.toLocaleString() : money(r.value)}</td><td>{r.unit}</td><td><span className={`data-badge ${r.provenance === "PUBLIC_PROXY" ? "proxy" : r.provenance === "REAL" ? "real" : "simulated"}`}>{r.provenance}</span></td><td>{r.source}</td></tr>)}</tbody></table></div><div className="source-strip"><span>PROVENANCE RULE</span><strong>REAL = direct provider / official feed · PUBLIC_PROXY = public benchmark · SIMULATED = test data</strong></div></section></div>;
}
