import { useEffect, useMemo, useState } from "react";
import { listCountries, listPorts, type Country, type Port } from "../api";
const code = (c: Country) => String(c.iso2 ?? c.country_code ?? c.code ?? "").slice(0, 2).toUpperCase();
export default function PortIntelligence() {
  const [countries, setCountries] = useState<Country[]>([]); const [country, setCountry] = useState("IN"); const [ports, setPorts] = useState<Port[]>([]); const [query, setQuery] = useState("");
  useEffect(() => { listCountries().then(setCountries).catch(() => undefined); }, []); useEffect(() => { listPorts(country).then(setPorts).catch(() => setPorts([])); }, [country]);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return ports.filter(p => !q || `${p.name} ${p.unlocode || ""}`.toLowerCase().includes(q)); }, [ports, query]); const selected = countries.find(c => code(c) === country);
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">OPERATIONS / PORT INTELLIGENCE</span><h1>Port Intelligence</h1><p>Country selection is the primary filter. Port records are loaded only for the selected country.</p></div><span className="data-badge proxy">UN/LOCODE FOUNDATION</span></div><section className="enterprise-card"><div className="form-grid two"><div className="field"><label>COUNTRY</label><select value={country} onChange={e => setCountry(e.target.value)}>{countries.map(c => <option key={c.id} value={code(c)}>{c.name} · {code(c)}{c.iso3 ? ` / ${c.iso3}` : ""}</option>)}</select></div><div className="field"><label>PORT SEARCH</label><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search port name or UN/LOCODE"/><small>{selected?.name || "Selected country"} · {ports.length.toLocaleString()} loaded records</small></div></div></section><section className="enterprise-card"><div className="section-head"><div><span className="eyebrow">PORT DIRECTORY</span><h2>{selected?.name || country} ports</h2></div><span className="field-note">{filtered.length.toLocaleString()} matches</span></div><div className="port-grid">{filtered.slice(0, 60).map(p => <article className="port-card" key={p.id}><div><strong>{p.name}</strong><span>{p.unlocode || "LOCODE unavailable"}</span></div><div className="port-facts"><span>{p.latitude?.toFixed(3) ?? "—"}° lat</span><span>{p.longitude?.toFixed(3) ?? "—"}° lon</span><span>Draft {p.max_draft_m ? `${p.max_draft_m} m` : "source pending"}</span></div><small>{p.source || "UNECE UN/LOCODE"} · {p.provenance || "PUBLIC_PROXY"}</small></article>)}</div>{filtered.length > 60 && <div className="source-strip">Showing first 60 matches. Search to narrow the country directory.</div>}</section></div>;
}
