import { useEffect, useMemo, useState } from "react";
import { listVessels, type Vessel } from "../api";
import { PUBLIC_VESSEL_REFERENCES } from "../data/publicMarket";
export default function VesselDirectory() {
  const [live, setLive] = useState<Vessel[]>([]); const [query, setQuery] = useState(""); const [klass, setKlass] = useState("ALL");
  useEffect(() => { listVessels().then(setLive).catch(() => setLive([])); }, []);
  const rows = useMemo(() => [...live.map(v => ({ name: v.name, className: v.vessel_class || v.ship_type || "Unknown", dwt: v.dwt, loa: v.loa_m, beam: v.beam_m, draft: v.max_draft_m, fuel: undefined as number | undefined, provenance: v.provenance, source: v.source || "API" })), ...PUBLIC_VESSEL_REFERENCES.map(v => ({ name: v.vessel, className: v.className, dwt: v.dwt, loa: v.loa, beam: v.beam, draft: v.draft, fuel: v.fuel, provenance: "PUBLIC_PROXY", source: v.source }))].filter(v => { const q = query.toLowerCase(); return (!q || `${v.name} ${v.className}`.toLowerCase().includes(q)) && (klass === "ALL" || v.className.toLowerCase().includes(klass.toLowerCase())); }), [live, query, klass]);
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">OPERATIONS / VESSEL INTELLIGENCE</span><h1>Vessel Directory</h1><p>Operational database records are shown alongside clearly labelled public reference vessels/class benchmarks.</p></div><span className="data-badge proxy">CLASS REFERENCE</span></div><section className="enterprise-card"><div className="form-grid two"><div className="field"><label>SEARCH VESSEL</label><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, IMO or vessel class"/></div><div className="field"><label>VESSEL CLASS</label><select value={klass} onChange={e => setKlass(e.target.value)}><option>ALL</option><option>Panamax</option><option>Capesize</option><option>Handysize</option></select></div></div></section><section className="enterprise-card"><div className="table-wrap"><table><thead><tr><th>Vessel / Reference</th><th>Class</th><th>DWT</th><th>LOA</th><th>Beam</th><th>Max draft</th><th>Fuel / day</th><th>Provenance</th></tr></thead><tbody>{rows.map((v, i) => <tr key={`${v.name}-${i}`}><td className="strong">{v.name}</td><td>{v.className}</td><td>{v.dwt?.toLocaleString() ?? "—"} MT</td><td>{v.loa ?? "—"} m</td><td>{v.beam ?? "—"} m</td><td>{v.draft ?? "—"} m</td><td>{v.fuel ? `${v.fuel} MT` : "—"}</td><td><span className={`data-badge ${v.provenance === "PUBLIC_PROXY" ? "proxy" : v.provenance === "REAL" ? "real" : "simulated"}`}>{v.provenance}</span></td></tr>)}</tbody></table></div><div className="source-strip">Fuel figures are reference consumption at stated operating conditions; they are not a live noon-report feed.</div></section></div>;
}
